IF
	!InMyArea("JOHADDUD")
	!Dead("JOHADDUD")
	Global("JOLoupgris_The_Night","GLOBAL",1)
	Global("JOLOUPAN_ISHERE","MYAREA",0)
	//TimeOfDay(NIGHT)
	See([PC])
THEN
	RESPONSE #100
		SetGlobal("JOLOUPAN_ISHERE","MYAREA",1)
		OpenDoor("DOOR09")
		Wait(2)
		CreateCreature("JOHADDUD",[%JOHADDUD_he%],0)
		CreateCreature("JOLOUPA2",[%JOHADDUD_place%],0)
		// CreateCreature("JOSLOUM2",[%JOHADDUD_place%],0)
		Wait(1)
		CloseDoor("DOOR09")
		Wait(1)
		DestroySelf()
END
